# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2020.10.15
# Revision...: --
# Purpose....: Docker compose file to create Guacamole setup
# Notes......: --
# Reference..: https://github.com/oehrlis/oudbase
# License....: Apache License Version 2.0, January 2004 as shown
#              at http://www.apache.org/licenses/
# ---------------------------------------------------------------------------

version: '3.5'
services:

# - guacd -------------------------------------------------------------------
    guacd:
        image: guacamole/guacd
        container_name: guacd
        restart: always
        volumes:
        - ${DOCKER_VOLUME_BASE}/data/guacd/drive:/drive:rw
        - ${DOCKER_VOLUME_BASE}/data/guacd/record:/record:rw
# - guacamole ---------------------------------------------------------------
    guacamole:
        image: guacamole/guacamole
        container_name: guacamole
        depends_on:
        - guacd
        - mysql
        environment:
            GUACD_HOSTNAME: guacd
            MYSQL_HOSTNAME: mysql
            MYSQL_DATABASE: guacadb
            MYSQL_USER: guacamole_user
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        links:
        - guacd
        ports:
        - 8080:8080/tcp
        restart: always

# - mysql ----------------------------------------------------------------
    mysql:
        image: mysql/mysql-server
        container_name: mysql
        environment:
            # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: guacamole_user
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: guacadb
        volumes:
            - ./config/mysql:/docker-entrypoint-initdb.d:ro
            - ${DOCKER_VOLUME_BASE}/data/mysql:/var/lib/mysql/:rw
# - EOF -----------------------------------------------------------------